theme: jekyll-theme-minimal
title: Calculator
description: Use the calculator to find, use and solve formulae with given data
<li class="masthead__menu-item">
          <a href="LaserSafety.github.io/calculator.html">Research</a>
        </li>
